# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_num', models.CharField(max_length=16)),
                ('block_id', models.IntegerField()),
                ('vehicle_id', models.IntegerField()),
                ('direction', models.CharField(max_length=16)),
                ('destination', models.CharField(max_length=128)),
                ('offset_sec', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('reported_at_utc', models.DateTimeField()),
                ('created_at_utc', models.DateTimeField()),
            ],
        ),
    ]
