# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_num', models.CharField(max_length=16)),
                ('direction', models.CharField(max_length=16)),
                ('hour_utc', models.IntegerField()),
                ('date_utc', models.DateField()),
                ('total_distance_m', models.IntegerField()),
                ('total_duration_s', models.IntegerField()),
                ('count_observations', models.IntegerField()),
                ('created_at_utc', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='offset_sec',
        ),
    ]
