# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 00:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170226_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationstat',
            name='reported_at_utc',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 26, 0, 21, 30, 381117, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
