# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_locationstat_reported_at_utc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationstat',
            name='date_utc',
        ),
    ]
