# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 00:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_locationstat_date_utc'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationstat',
            name='updated_at_utc',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 27, 0, 46, 40, 967636, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='locationstat',
            unique_together=set([('route_num', 'direction', 'hour_utc')]),
        ),
    ]
