# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170227_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationstat',
            name='reported_at_utc',
        ),
        migrations.AddField(
            model_name='locationstat',
            name='date_utc',
            field=models.DateField(null=True),
        ),
    ]
