# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_locationstat_updated_at_utc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationstat',
            name='date_utc',
            field=models.DateField(),
        ),
    ]
